// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: salutoni.proto
// Protobuf Java Version: 4.31.1

package ciaoooo;

@com.google.protobuf.Generated
public final class Salutoni {
  private Salutoni() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      Salutoni.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface stringMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ciaoooo.stringMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string contenuto = 1;</code>
     * @return The contenuto.
     */
    java.lang.String getContenuto();
    /**
     * <code>string contenuto = 1;</code>
     * @return The bytes for contenuto.
     */
    com.google.protobuf.ByteString
        getContenutoBytes();
  }
  /**
   * Protobuf type {@code ciaoooo.stringMessage}
   */
  public static final class stringMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ciaoooo.stringMessage)
      stringMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        stringMessage.class.getName());
    }
    // Use stringMessage.newBuilder() to construct.
    private stringMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private stringMessage() {
      contenuto_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ciaoooo.Salutoni.internal_static_ciaoooo_stringMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ciaoooo.Salutoni.internal_static_ciaoooo_stringMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ciaoooo.Salutoni.stringMessage.class, ciaoooo.Salutoni.stringMessage.Builder.class);
    }

    public static final int CONTENUTO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object contenuto_ = "";
    /**
     * <code>string contenuto = 1;</code>
     * @return The contenuto.
     */
    @java.lang.Override
    public java.lang.String getContenuto() {
      java.lang.Object ref = contenuto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contenuto_ = s;
        return s;
      }
    }
    /**
     * <code>string contenuto = 1;</code>
     * @return The bytes for contenuto.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getContenutoBytes() {
      java.lang.Object ref = contenuto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contenuto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contenuto_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, contenuto_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(contenuto_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, contenuto_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ciaoooo.Salutoni.stringMessage)) {
        return super.equals(obj);
      }
      ciaoooo.Salutoni.stringMessage other = (ciaoooo.Salutoni.stringMessage) obj;

      if (!getContenuto()
          .equals(other.getContenuto())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENUTO_FIELD_NUMBER;
      hash = (53 * hash) + getContenuto().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ciaoooo.Salutoni.stringMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ciaoooo.Salutoni.stringMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ciaoooo.Salutoni.stringMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ciaoooo.Salutoni.stringMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ciaoooo.Salutoni.stringMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ciaoooo.stringMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ciaoooo.stringMessage)
        ciaoooo.Salutoni.stringMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ciaoooo.Salutoni.internal_static_ciaoooo_stringMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ciaoooo.Salutoni.internal_static_ciaoooo_stringMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ciaoooo.Salutoni.stringMessage.class, ciaoooo.Salutoni.stringMessage.Builder.class);
      }

      // Construct using ciaoooo.Salutoni.stringMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        contenuto_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ciaoooo.Salutoni.internal_static_ciaoooo_stringMessage_descriptor;
      }

      @java.lang.Override
      public ciaoooo.Salutoni.stringMessage getDefaultInstanceForType() {
        return ciaoooo.Salutoni.stringMessage.getDefaultInstance();
      }

      @java.lang.Override
      public ciaoooo.Salutoni.stringMessage build() {
        ciaoooo.Salutoni.stringMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ciaoooo.Salutoni.stringMessage buildPartial() {
        ciaoooo.Salutoni.stringMessage result = new ciaoooo.Salutoni.stringMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ciaoooo.Salutoni.stringMessage result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.contenuto_ = contenuto_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ciaoooo.Salutoni.stringMessage) {
          return mergeFrom((ciaoooo.Salutoni.stringMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ciaoooo.Salutoni.stringMessage other) {
        if (other == ciaoooo.Salutoni.stringMessage.getDefaultInstance()) return this;
        if (!other.getContenuto().isEmpty()) {
          contenuto_ = other.contenuto_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                contenuto_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object contenuto_ = "";
      /**
       * <code>string contenuto = 1;</code>
       * @return The contenuto.
       */
      public java.lang.String getContenuto() {
        java.lang.Object ref = contenuto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contenuto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string contenuto = 1;</code>
       * @return The bytes for contenuto.
       */
      public com.google.protobuf.ByteString
          getContenutoBytes() {
        java.lang.Object ref = contenuto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contenuto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string contenuto = 1;</code>
       * @param value The contenuto to set.
       * @return This builder for chaining.
       */
      public Builder setContenuto(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        contenuto_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string contenuto = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearContenuto() {
        contenuto_ = getDefaultInstance().getContenuto();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string contenuto = 1;</code>
       * @param value The bytes for contenuto to set.
       * @return This builder for chaining.
       */
      public Builder setContenutoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        contenuto_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ciaoooo.stringMessage)
    }

    // @@protoc_insertion_point(class_scope:ciaoooo.stringMessage)
    private static final ciaoooo.Salutoni.stringMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ciaoooo.Salutoni.stringMessage();
    }

    public static ciaoooo.Salutoni.stringMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<stringMessage>
        PARSER = new com.google.protobuf.AbstractParser<stringMessage>() {
      @java.lang.Override
      public stringMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<stringMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<stringMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ciaoooo.Salutoni.stringMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ciaoooo_stringMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ciaoooo_stringMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016salutoni.proto\022\007ciaoooo\"\"\n\rstringMessa" +
      "ge\022\021\n\tcontenuto\030\001 \001(\t2E\n\007Greeter\022:\n\010sayH" +
      "ello\022\026.ciaoooo.stringMessage\032\026.ciaoooo.s" +
      "tringMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ciaoooo_stringMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ciaoooo_stringMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ciaoooo_stringMessage_descriptor,
        new java.lang.String[] { "Contenuto", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
