# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\"#\n\x0bSensorsMean\x12\x14\n\x0csensors_mean\x18\x01 \x01(\x02\"\x07\n\x05\x45mpty\".\n\x06Sensor\x12\x11\n\tsensor_id\x18\x01 \x01(\x03\x12\x11\n\tdata_type\x18\x02 \x01(\t2\x82\x01\n\x11StatisticsManager\x12\x35\n\ngetSensors\x12\x11.statistics.Empty\x1a\x12.statistics.Sensor0\x01\x12\x36\n\x07getMean\x12\x12.statistics.Sensor\x1a\x17.statistics.SensorsMeanb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORSMEAN']._serialized_start=32
  _globals['_SENSORSMEAN']._serialized_end=67
  _globals['_EMPTY']._serialized_start=69
  _globals['_EMPTY']._serialized_end=76
  _globals['_SENSOR']._serialized_start=78
  _globals['_SENSOR']._serialized_end=124
  _globals['_STATISTICSMANAGER']._serialized_start=127
  _globals['_STATISTICSMANAGER']._serialized_end=257
# @@protoc_insertion_point(module_scope)
