# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temperature.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11temperature.proto\x12\nmioPackage\",\n\x15Richiesta_temperatura\x12\x13\n\x0btemperatura\x18\x01 \x01(\x05\"\x1e\n\x0fRisposta_string\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x11\n\x0fRichiesta_vuota\"\x1f\n\x0eRisposta_float\x12\r\n\x05media\x18\x01 \x01(\x02\x32\xa3\x01\n\x08Gestione\x12O\n\x0bstream_temp\x12!.mioPackage.Richiesta_temperatura\x1a\x1b.mioPackage.Risposta_string(\x01\x12\x46\n\x0bget_average\x12\x1b.mioPackage.Richiesta_vuota\x1a\x1a.mioPackage.Risposta_floatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperature_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RICHIESTA_TEMPERATURA']._serialized_start=33
  _globals['_RICHIESTA_TEMPERATURA']._serialized_end=77
  _globals['_RISPOSTA_STRING']._serialized_start=79
  _globals['_RISPOSTA_STRING']._serialized_end=109
  _globals['_RICHIESTA_VUOTA']._serialized_start=111
  _globals['_RICHIESTA_VUOTA']._serialized_end=128
  _globals['_RISPOSTA_FLOAT']._serialized_start=130
  _globals['_RISPOSTA_FLOAT']._serialized_end=161
  _globals['_GESTIONE']._serialized_start=164
  _globals['_GESTIONE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
