# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_management.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16order_management.proto\x12\tecommerce\"[\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05items\x18\x02 \x03(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x05 \x01(\t\" \n\rStringMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"O\n\x10\x43ombinedShipment\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05stato\x18\x02 \x01(\t\x12 \n\x06orders\x18\x03 \x03(\x0b\x32\x10.ecommerce.Order2\x83\x02\n\x0fOrderManagement\x12\x36\n\x08\x61\x64\x64Order\x12\x10.ecommerce.Order\x1a\x18.ecommerce.StringMessage\x12\x36\n\x08getOrder\x12\x18.ecommerce.StringMessage\x1a\x10.ecommerce.Order\x12<\n\x0csearchOrders\x12\x18.ecommerce.StringMessage\x1a\x10.ecommerce.Order0\x01\x12\x42\n\rprocessorders\x12\x10.ecommerce.Order\x1a\x1b.ecommerce.CombinedShipment(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_management_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=37
  _globals['_ORDER']._serialized_end=128
  _globals['_STRINGMESSAGE']._serialized_start=130
  _globals['_STRINGMESSAGE']._serialized_end=162
  _globals['_COMBINEDSHIPMENT']._serialized_start=164
  _globals['_COMBINEDSHIPMENT']._serialized_end=243
  _globals['_ORDERMANAGEMENT']._serialized_start=246
  _globals['_ORDERMANAGEMENT']._serialized_end=505
# @@protoc_insertion_point(module_scope)
