# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import order_management_pb2 as order__management__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class OrderManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addOrder = channel.unary_unary(
                '/ecommerce.OrderManagement/addOrder',
                request_serializer=order__management__pb2.Order.SerializeToString,
                response_deserializer=order__management__pb2.StringMessage.FromString,
                _registered_method=True)
        self.getOrder = channel.unary_unary(
                '/ecommerce.OrderManagement/getOrder',
                request_serializer=order__management__pb2.StringMessage.SerializeToString,
                response_deserializer=order__management__pb2.Order.FromString,
                _registered_method=True)
        self.searchOrders = channel.unary_stream(
                '/ecommerce.OrderManagement/searchOrders',
                request_serializer=order__management__pb2.StringMessage.SerializeToString,
                response_deserializer=order__management__pb2.Order.FromString,
                _registered_method=True)
        self.processorders = channel.stream_stream(
                '/ecommerce.OrderManagement/processorders',
                request_serializer=order__management__pb2.Order.SerializeToString,
                response_deserializer=order__management__pb2.CombinedShipment.FromString,
                _registered_method=True)


class OrderManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def searchOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def processorders(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.addOrder,
                    request_deserializer=order__management__pb2.Order.FromString,
                    response_serializer=order__management__pb2.StringMessage.SerializeToString,
            ),
            'getOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.getOrder,
                    request_deserializer=order__management__pb2.StringMessage.FromString,
                    response_serializer=order__management__pb2.Order.SerializeToString,
            ),
            'searchOrders': grpc.unary_stream_rpc_method_handler(
                    servicer.searchOrders,
                    request_deserializer=order__management__pb2.StringMessage.FromString,
                    response_serializer=order__management__pb2.Order.SerializeToString,
            ),
            'processorders': grpc.stream_stream_rpc_method_handler(
                    servicer.processorders,
                    request_deserializer=order__management__pb2.Order.FromString,
                    response_serializer=order__management__pb2.CombinedShipment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ecommerce.OrderManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ecommerce.OrderManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.OrderManagement/addOrder',
            order__management__pb2.Order.SerializeToString,
            order__management__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ecommerce.OrderManagement/getOrder',
            order__management__pb2.StringMessage.SerializeToString,
            order__management__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def searchOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ecommerce.OrderManagement/searchOrders',
            order__management__pb2.StringMessage.SerializeToString,
            order__management__pb2.Order.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def processorders(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ecommerce.OrderManagement/processorders',
            order__management__pb2.Order.SerializeToString,
            order__management__pb2.CombinedShipment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
