// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GestioneTask.proto
// Protobuf Java Version: 4.31.1

package PackageTask;

@com.google.protobuf.Generated
public final class GestioneTaskOuterClass {
  private GestioneTaskOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      GestioneTaskOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageTask_Req_task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PackageTask_Req_task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageTask_Res_void_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PackageTask_Res_void_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackageTask_Req_string_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PackageTask_Req_string_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022GestioneTask.proto\022\013PackageTask\"2\n\010Req" +
      "_task\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030" +
      "\003 \001(\t\"\n\n\010Res_void\"\032\n\nReq_string\022\014\n\004type\030" +
      "\001 \001(\t2\202\001\n\014GestioneTask\0226\n\006deploy\022\025.Packa" +
      "geTask.Req_task\032\025.PackageTask.Res_void\022:" +
      "\n\010stop_all\022\027.PackageTask.Req_string\032\025.Pa" +
      "ckageTask.Res_voidB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PackageTask_Req_task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PackageTask_Req_task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PackageTask_Req_task_descriptor,
        new java.lang.String[] { "Id", "Name", "Type", });
    internal_static_PackageTask_Res_void_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PackageTask_Res_void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PackageTask_Res_void_descriptor,
        new java.lang.String[] { });
    internal_static_PackageTask_Req_string_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PackageTask_Req_string_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PackageTask_Req_string_descriptor,
        new java.lang.String[] { "Type", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
