// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GestioneTask.proto
// Protobuf Java Version: 4.31.1

package PackageTask;

@com.google.protobuf.Generated
public interface Req_stringOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PackageTask.Req_string)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * gpu-bound o real-time
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * gpu-bound o real-time
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
