// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: GestioneTask.proto
// Protobuf Java Version: 4.31.1

package PackageTask;

@com.google.protobuf.Generated
public interface Res_voidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PackageTask.Res_void)
    com.google.protobuf.MessageOrBuilder {
}
