# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import Laboratori_pb2 as Laboratori__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in Laboratori_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GestioneLabStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.book = channel.unary_unary(
                '/mioPackage.GestioneLab/book',
                request_serializer=Laboratori__pb2.Msg_labnumber.SerializeToString,
                response_deserializer=Laboratori__pb2.Ack.FromString,
                _registered_method=True)
        self.delete = channel.unary_unary(
                '/mioPackage.GestioneLab/delete',
                request_serializer=Laboratori__pb2.Empty.SerializeToString,
                response_deserializer=Laboratori__pb2.Msg_labnumber.FromString,
                _registered_method=True)


class GestioneLabServicer(object):
    """Missing associated documentation comment in .proto file."""

    def book(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestioneLabServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'book': grpc.unary_unary_rpc_method_handler(
                    servicer.book,
                    request_deserializer=Laboratori__pb2.Msg_labnumber.FromString,
                    response_serializer=Laboratori__pb2.Ack.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=Laboratori__pb2.Empty.FromString,
                    response_serializer=Laboratori__pb2.Msg_labnumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mioPackage.GestioneLab', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mioPackage.GestioneLab', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestioneLab(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def book(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mioPackage.GestioneLab/book',
            Laboratori__pb2.Msg_labnumber.SerializeToString,
            Laboratori__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mioPackage.GestioneLab/delete',
            Laboratori__pb2.Empty.SerializeToString,
            Laboratori__pb2.Msg_labnumber.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
