# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Laboratori.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Laboratori.proto\x12\nmioPackage\"#\n\rMsg_labnumber\x12\x12\n\nlab_number\x18\x01 \x01(\x05\"\x12\n\x03\x41\x63k\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2y\n\x0bGestioneLab\x12\x32\n\x04\x62ook\x12\x19.mioPackage.Msg_labnumber\x1a\x0f.mioPackage.Ack\x12\x36\n\x06\x64\x65lete\x12\x11.mioPackage.Empty\x1a\x19.mioPackage.Msg_labnumberb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Laboratori_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_LABNUMBER']._serialized_start=32
  _globals['_MSG_LABNUMBER']._serialized_end=67
  _globals['_ACK']._serialized_start=69
  _globals['_ACK']._serialized_end=87
  _globals['_EMPTY']._serialized_start=89
  _globals['_EMPTY']._serialized_end=96
  _globals['_GESTIONELAB']._serialized_start=98
  _globals['_GESTIONELAB']._serialized_end=219
# @@protoc_insertion_point(module_scope)
