# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistiche.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11statistiche.proto\x12\nmioPackage\"\'\n\x06Sensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\",\n\x0bMeanRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tdata_type\x18\x02 \x01(\t\"\x1e\n\rStringMessage\x12\r\n\x05media\x18\x01 \x01(\x02\"\x07\n\x05\x45mpty2\x83\x01\n\x0bStatistiche\x12\x35\n\ngetSensors\x12\x11.mioPackage.Empty\x1a\x12.mioPackage.Sensor0\x01\x12=\n\x07getMean\x12\x17.mioPackage.MeanRequest\x1a\x19.mioPackage.StringMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistiche_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSOR']._serialized_start=33
  _globals['_SENSOR']._serialized_end=72
  _globals['_MEANREQUEST']._serialized_start=74
  _globals['_MEANREQUEST']._serialized_end=118
  _globals['_STRINGMESSAGE']._serialized_start=120
  _globals['_STRINGMESSAGE']._serialized_end=150
  _globals['_EMPTY']._serialized_start=152
  _globals['_EMPTY']._serialized_end=159
  _globals['_STATISTICHE']._serialized_start=162
  _globals['_STATISTICHE']._serialized_end=293
# @@protoc_insertion_point(module_scope)
