# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mioPrimoIDL.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11mioPrimoIDL.proto\x12\x04gRPC\"\x1d\n\x08msgInvio\x12\x11\n\tcontenuto\x18\x01 \x01(\t\"\x1f\n\nmsgRitorno\x12\x11\n\tcontenuto\x18\x01 \x01(\t26\n\x06\x43iaone\x12,\n\x08\x64iciCiao\x12\x0e.gRPC.msgInvio\x1a\x10.gRPC.msgRitornob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mioPrimoIDL_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSGINVIO']._serialized_start=27
  _globals['_MSGINVIO']._serialized_end=56
  _globals['_MSGRITORNO']._serialized_start=58
  _globals['_MSGRITORNO']._serialized_end=89
  _globals['_CIAONE']._serialized_start=91
  _globals['_CIAONE']._serialized_end=145
# @@protoc_insertion_point(module_scope)
