# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import helloworld_pb2 as helloworld__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in helloworld_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class GreeterStub(object):   #⭕ il client ne creerà un'istanza per comunicare!
    """c'è semplicemente servizio say hello che prende una stringa e ritorna una stringa

    specifica IDL del mio servizio HELLOWORLD
    qui ho lista di chiamate RPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(  #⭕useremo (e creeremo) concetto di canale per la comunicazione -> semantica particolare per la chiamata a procedura remota | in gRPC posso avere combinazione di semantiche tc {4 combinazioni di messaggio richiesta/risposta} es STREAM_UNARY ecc
                '/helloworld.Greeter/SayHello', #⭕funzione definita nello spazio dei nomi da package e service
                request_serializer=helloworld__pb2.HelloRequest.SerializeToString, #⭕come serializzare e de-serializzare messaggio da servente, può variare al tipo del messaggio da specificare
                response_deserializer=helloworld__pb2.HelloReply.FromString,
                _registered_method=True)


class GreeterServicer(object): #⭕Non è una classe astratta in termini ABC, ma comunque mappabile come classe astratta
    """c'è semplicemente servizio say hello che prende una stringa e ritorna una stringa

    specifica IDL del mio servizio HELLOWORLD
    qui ho lista di chiamate RPC
    """

    def SayHello(self, request, context):
        """consiglio: usa messaggi che siano semanticamente espliciti
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!') #⭕Mi fa pensare che qualche classe debba implementare/estendere tale classe per poter gestire errore [l'implementatore appunto]


def add_GreeterServicer_to_server(servicer, server): #⭕metodo generato automaticamente | dice che devo aggiungere un servicer al mio server (è un oggetto rpc_server che mi permette di ascoltare le richieste a procedura remota)
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=helloworld__pb2.HelloRequest.FromString,
                    response_serializer=helloworld__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('helloworld.Greeter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """c'è semplicemente servizio say hello che prende una stringa e ritorna una stringa

    specifica IDL del mio servizio HELLOWORLD
    qui ho lista di chiamate RPC
    """

    @staticmethod
    def SayHello(request,  #⭕parte sperimentale che non mi interessa più di tanto
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/helloworld.Greeter/SayHello',
            helloworld__pb2.HelloRequest.SerializeToString,
            helloworld__pb2.HelloReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
