# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Laptop.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cLaptop.proto\x12\nmioPackage\"\n\n\x08msg_Void\"#\n\nmsg_Laptop\x12\x15\n\rserial_number\x18\x01 \x01(\x05\"\x16\n\x07msg_ack\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32y\n\rCompravendita\x12\x33\n\x03\x62uy\x12\x14.mioPackage.msg_Void\x1a\x16.mioPackage.msg_Laptop\x12\x33\n\x04sell\x12\x16.mioPackage.msg_Laptop\x1a\x13.mioPackage.msg_ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Laptop_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_VOID']._serialized_start=28
  _globals['_MSG_VOID']._serialized_end=38
  _globals['_MSG_LAPTOP']._serialized_start=40
  _globals['_MSG_LAPTOP']._serialized_end=75
  _globals['_MSG_ACK']._serialized_start=77
  _globals['_MSG_ACK']._serialized_end=99
  _globals['_COMPRAVENDITA']._serialized_start=101
  _globals['_COMPRAVENDITA']._serialized_end=222
# @@protoc_insertion_point(module_scope)
