# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Orchestration.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Orchestration.proto\x12\nmioPackage\"%\n\x07msg_req\x12\x0c\n\x04task\x18\x01 \x01(\t\x12\x0c\n\x04tipo\x18\x02 \x01(\t\"\x1a\n\x07msg_res\x12\x0f\n\x07ritorno\x18\x01 \x01(\t2J\n\rOrchestration\x12\x39\n\x0borchestrate\x12\x13.mioPackage.msg_req\x1a\x13.mioPackage.msg_res(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Orchestration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MSG_REQ']._serialized_start=35
  _globals['_MSG_REQ']._serialized_end=72
  _globals['_MSG_RES']._serialized_start=74
  _globals['_MSG_RES']._serialized_end=100
  _globals['_ORCHESTRATION']._serialized_start=102
  _globals['_ORCHESTRATION']._serialized_end=176
# @@protoc_insertion_point(module_scope)
