# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import statistiche_pb2 as statistiche__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in statistiche_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class StatisticheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSensors = channel.unary_stream(
                '/mioPackage.Statistiche/getSensors',
                request_serializer=statistiche__pb2.Empty.SerializeToString,
                response_deserializer=statistiche__pb2.Sensor.FromString,
                _registered_method=True)
        self.getMean = channel.unary_unary(
                '/mioPackage.Statistiche/getMean',
                request_serializer=statistiche__pb2.MeanRequest.SerializeToString,
                response_deserializer=statistiche__pb2.StringMessage.FromString,
                _registered_method=True)


class StatisticheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSensors': grpc.unary_stream_rpc_method_handler(
                    servicer.getSensors,
                    request_deserializer=statistiche__pb2.Empty.FromString,
                    response_serializer=statistiche__pb2.Sensor.SerializeToString,
            ),
            'getMean': grpc.unary_unary_rpc_method_handler(
                    servicer.getMean,
                    request_deserializer=statistiche__pb2.MeanRequest.FromString,
                    response_serializer=statistiche__pb2.StringMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mioPackage.Statistiche', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mioPackage.Statistiche', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Statistiche(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(  # pyright: ignore[reportAttributeAccessIssue]
            request,
            target,
            '/mioPackage.Statistiche/getSensors',
            statistiche__pb2.Empty.SerializeToString,
            statistiche__pb2.Sensor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(  # pyright: ignore[reportAttributeAccessIssue]
            request,
            target,
            '/mioPackage.Statistiche/getMean',
            statistiche__pb2.MeanRequest.SerializeToString,
            statistiche__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
