// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: IJobUser.proto
// Protobuf Java Version: 4.31.1

package mioPackage;

@com.google.protobuf.Generated
public final class IJobUser {
  private IJobUser() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      IJobUser.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface msg_reqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mioPackage.msg_req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nomeJob = 1;</code>
     * @return The nomeJob.
     */
    java.lang.String getNomeJob();
    /**
     * <code>string nomeJob = 1;</code>
     * @return The bytes for nomeJob.
     */
    com.google.protobuf.ByteString
        getNomeJobBytes();

    /**
     * <code>int32 tipoProcessing = 2;</code>
     * @return The tipoProcessing.
     */
    int getTipoProcessing();

    /**
     * <code>string nomeFile = 3;</code>
     * @return The nomeFile.
     */
    java.lang.String getNomeFile();
    /**
     * <code>string nomeFile = 3;</code>
     * @return The bytes for nomeFile.
     */
    com.google.protobuf.ByteString
        getNomeFileBytes();
  }
  /**
   * Protobuf type {@code mioPackage.msg_req}
   */
  public static final class msg_req extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:mioPackage.msg_req)
      msg_reqOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        msg_req.class.getName());
    }
    // Use msg_req.newBuilder() to construct.
    private msg_req(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private msg_req() {
      nomeJob_ = "";
      nomeFile_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mioPackage.IJobUser.internal_static_mioPackage_msg_req_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mioPackage.IJobUser.internal_static_mioPackage_msg_req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mioPackage.IJobUser.msg_req.class, mioPackage.IJobUser.msg_req.Builder.class);
    }

    public static final int NOMEJOB_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nomeJob_ = "";
    /**
     * <code>string nomeJob = 1;</code>
     * @return The nomeJob.
     */
    @java.lang.Override
    public java.lang.String getNomeJob() {
      java.lang.Object ref = nomeJob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeJob_ = s;
        return s;
      }
    }
    /**
     * <code>string nomeJob = 1;</code>
     * @return The bytes for nomeJob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeJobBytes() {
      java.lang.Object ref = nomeJob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeJob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIPOPROCESSING_FIELD_NUMBER = 2;
    private int tipoProcessing_ = 0;
    /**
     * <code>int32 tipoProcessing = 2;</code>
     * @return The tipoProcessing.
     */
    @java.lang.Override
    public int getTipoProcessing() {
      return tipoProcessing_;
    }

    public static final int NOMEFILE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object nomeFile_ = "";
    /**
     * <code>string nomeFile = 3;</code>
     * @return The nomeFile.
     */
    @java.lang.Override
    public java.lang.String getNomeFile() {
      java.lang.Object ref = nomeFile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nomeFile_ = s;
        return s;
      }
    }
    /**
     * <code>string nomeFile = 3;</code>
     * @return The bytes for nomeFile.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNomeFileBytes() {
      java.lang.Object ref = nomeFile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nomeFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeJob_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, nomeJob_);
      }
      if (tipoProcessing_ != 0) {
        output.writeInt32(2, tipoProcessing_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeFile_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, nomeFile_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeJob_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, nomeJob_);
      }
      if (tipoProcessing_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tipoProcessing_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(nomeFile_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, nomeFile_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mioPackage.IJobUser.msg_req)) {
        return super.equals(obj);
      }
      mioPackage.IJobUser.msg_req other = (mioPackage.IJobUser.msg_req) obj;

      if (!getNomeJob()
          .equals(other.getNomeJob())) return false;
      if (getTipoProcessing()
          != other.getTipoProcessing()) return false;
      if (!getNomeFile()
          .equals(other.getNomeFile())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOMEJOB_FIELD_NUMBER;
      hash = (53 * hash) + getNomeJob().hashCode();
      hash = (37 * hash) + TIPOPROCESSING_FIELD_NUMBER;
      hash = (53 * hash) + getTipoProcessing();
      hash = (37 * hash) + NOMEFILE_FIELD_NUMBER;
      hash = (53 * hash) + getNomeFile().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mioPackage.IJobUser.msg_req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static mioPackage.IJobUser.msg_req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static mioPackage.IJobUser.msg_req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static mioPackage.IJobUser.msg_req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mioPackage.IJobUser.msg_req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mioPackage.msg_req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mioPackage.msg_req)
        mioPackage.IJobUser.msg_reqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_req_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mioPackage.IJobUser.msg_req.class, mioPackage.IJobUser.msg_req.Builder.class);
      }

      // Construct using mioPackage.IJobUser.msg_req.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        nomeJob_ = "";
        tipoProcessing_ = 0;
        nomeFile_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_req_descriptor;
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_req getDefaultInstanceForType() {
        return mioPackage.IJobUser.msg_req.getDefaultInstance();
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_req build() {
        mioPackage.IJobUser.msg_req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_req buildPartial() {
        mioPackage.IJobUser.msg_req result = new mioPackage.IJobUser.msg_req(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(mioPackage.IJobUser.msg_req result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.nomeJob_ = nomeJob_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tipoProcessing_ = tipoProcessing_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.nomeFile_ = nomeFile_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mioPackage.IJobUser.msg_req) {
          return mergeFrom((mioPackage.IJobUser.msg_req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mioPackage.IJobUser.msg_req other) {
        if (other == mioPackage.IJobUser.msg_req.getDefaultInstance()) return this;
        if (!other.getNomeJob().isEmpty()) {
          nomeJob_ = other.nomeJob_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getTipoProcessing() != 0) {
          setTipoProcessing(other.getTipoProcessing());
        }
        if (!other.getNomeFile().isEmpty()) {
          nomeFile_ = other.nomeFile_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                nomeJob_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                tipoProcessing_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                nomeFile_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object nomeJob_ = "";
      /**
       * <code>string nomeJob = 1;</code>
       * @return The nomeJob.
       */
      public java.lang.String getNomeJob() {
        java.lang.Object ref = nomeJob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeJob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nomeJob = 1;</code>
       * @return The bytes for nomeJob.
       */
      public com.google.protobuf.ByteString
          getNomeJobBytes() {
        java.lang.Object ref = nomeJob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeJob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nomeJob = 1;</code>
       * @param value The nomeJob to set.
       * @return This builder for chaining.
       */
      public Builder setNomeJob(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nomeJob_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string nomeJob = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeJob() {
        nomeJob_ = getDefaultInstance().getNomeJob();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string nomeJob = 1;</code>
       * @param value The bytes for nomeJob to set.
       * @return This builder for chaining.
       */
      public Builder setNomeJobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nomeJob_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int tipoProcessing_ ;
      /**
       * <code>int32 tipoProcessing = 2;</code>
       * @return The tipoProcessing.
       */
      @java.lang.Override
      public int getTipoProcessing() {
        return tipoProcessing_;
      }
      /**
       * <code>int32 tipoProcessing = 2;</code>
       * @param value The tipoProcessing to set.
       * @return This builder for chaining.
       */
      public Builder setTipoProcessing(int value) {

        tipoProcessing_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tipoProcessing = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTipoProcessing() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tipoProcessing_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nomeFile_ = "";
      /**
       * <code>string nomeFile = 3;</code>
       * @return The nomeFile.
       */
      public java.lang.String getNomeFile() {
        java.lang.Object ref = nomeFile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nomeFile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nomeFile = 3;</code>
       * @return The bytes for nomeFile.
       */
      public com.google.protobuf.ByteString
          getNomeFileBytes() {
        java.lang.Object ref = nomeFile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nomeFile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nomeFile = 3;</code>
       * @param value The nomeFile to set.
       * @return This builder for chaining.
       */
      public Builder setNomeFile(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        nomeFile_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string nomeFile = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNomeFile() {
        nomeFile_ = getDefaultInstance().getNomeFile();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string nomeFile = 3;</code>
       * @param value The bytes for nomeFile to set.
       * @return This builder for chaining.
       */
      public Builder setNomeFileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        nomeFile_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mioPackage.msg_req)
    }

    // @@protoc_insertion_point(class_scope:mioPackage.msg_req)
    private static final mioPackage.IJobUser.msg_req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mioPackage.IJobUser.msg_req();
    }

    public static mioPackage.IJobUser.msg_req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_req>
        PARSER = new com.google.protobuf.AbstractParser<msg_req>() {
      @java.lang.Override
      public msg_req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<msg_req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_req> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mioPackage.IJobUser.msg_req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface msg_emptyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mioPackage.msg_empty)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mioPackage.msg_empty}
   */
  public static final class msg_empty extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:mioPackage.msg_empty)
      msg_emptyOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        msg_empty.class.getName());
    }
    // Use msg_empty.newBuilder() to construct.
    private msg_empty(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private msg_empty() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mioPackage.IJobUser.internal_static_mioPackage_msg_empty_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mioPackage.IJobUser.internal_static_mioPackage_msg_empty_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mioPackage.IJobUser.msg_empty.class, mioPackage.IJobUser.msg_empty.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mioPackage.IJobUser.msg_empty)) {
        return super.equals(obj);
      }
      mioPackage.IJobUser.msg_empty other = (mioPackage.IJobUser.msg_empty) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mioPackage.IJobUser.msg_empty parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static mioPackage.IJobUser.msg_empty parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static mioPackage.IJobUser.msg_empty parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static mioPackage.IJobUser.msg_empty parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mioPackage.IJobUser.msg_empty prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mioPackage.msg_empty}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mioPackage.msg_empty)
        mioPackage.IJobUser.msg_emptyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_empty_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_empty_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mioPackage.IJobUser.msg_empty.class, mioPackage.IJobUser.msg_empty.Builder.class);
      }

      // Construct using mioPackage.IJobUser.msg_empty.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mioPackage.IJobUser.internal_static_mioPackage_msg_empty_descriptor;
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_empty getDefaultInstanceForType() {
        return mioPackage.IJobUser.msg_empty.getDefaultInstance();
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_empty build() {
        mioPackage.IJobUser.msg_empty result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mioPackage.IJobUser.msg_empty buildPartial() {
        mioPackage.IJobUser.msg_empty result = new mioPackage.IJobUser.msg_empty(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mioPackage.IJobUser.msg_empty) {
          return mergeFrom((mioPackage.IJobUser.msg_empty)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mioPackage.IJobUser.msg_empty other) {
        if (other == mioPackage.IJobUser.msg_empty.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mioPackage.msg_empty)
    }

    // @@protoc_insertion_point(class_scope:mioPackage.msg_empty)
    private static final mioPackage.IJobUser.msg_empty DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mioPackage.IJobUser.msg_empty();
    }

    public static mioPackage.IJobUser.msg_empty getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<msg_empty>
        PARSER = new com.google.protobuf.AbstractParser<msg_empty>() {
      @java.lang.Override
      public msg_empty parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<msg_empty> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<msg_empty> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mioPackage.IJobUser.msg_empty getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mioPackage_msg_req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mioPackage_msg_req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mioPackage_msg_empty_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mioPackage_msg_empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016IJobUser.proto\022\nmioPackage\"D\n\007msg_req\022" +
      "\017\n\007nomeJob\030\001 \001(\t\022\026\n\016tipoProcessing\030\002 \001(\005" +
      "\022\020\n\010nomeFile\030\003 \001(\t\"\013\n\tmsg_empty2=\n\004Jobs\022" +
      "5\n\007job_req\022\023.mioPackage.msg_req\032\025.mioPac" +
      "kage.msg_emptyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mioPackage_msg_req_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mioPackage_msg_req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mioPackage_msg_req_descriptor,
        new java.lang.String[] { "NomeJob", "TipoProcessing", "NomeFile", });
    internal_static_mioPackage_msg_empty_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mioPackage_msg_empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mioPackage_msg_empty_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
