# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IValidationHub.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14IValidationHub.proto\x12\nmioPackage\"U\n\tCodeChunk\x12\x11\n\tprojectId\x18\x01 \x01(\t\x12\x10\n\x08\x66ileName\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x12\n\nchunkIndex\x18\x04 \x01(\x05\"\"\n\x10ValidationResult\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32T\n\nValidation\x12\x46\n\rsubmitProject\x12\x15.mioPackage.CodeChunk\x1a\x1c.mioPackage.ValidationResult(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IValidationHub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODECHUNK']._serialized_start=36
  _globals['_CODECHUNK']._serialized_end=121
  _globals['_VALIDATIONRESULT']._serialized_start=123
  _globals['_VALIDATIONRESULT']._serialized_end=157
  _globals['_VALIDATION']._serialized_start=159
  _globals['_VALIDATION']._serialized_end=243
# @@protoc_insertion_point(module_scope)
